### ISSUE TITLE
Extracting *.rhd NeuroNexus data into Python

### ISSUE THREAD

**Issue by IljaPilja** [kylerbrown/rhd#2]
Hi,
after spending a seeming eternity to install "rhd", I'm faced with a MemoryError. I used the "no_floats = True" but the error still occurs. My data consists of 2-3 min recordings at 20 kHz and till now I've been using Matlab to convert but part of my analysis I perform in Python so it would be more convenient to import into Python immediately. I use the following code to start the program of:
`data = rhd.load_intan_rhd_format.read_data(r"C:\Users\dsuchane\Documents\SmartBoxData\SmartboxRecording_20180415-143252.rhd", no_floats=True)`

Then the console states the following information:
`Reading Intan Technologies RHD2000 Data File, Version 1.4
Found 64 amplifier channels.
Traceback (most recent call last):
Found 0 auxiliary input channels.
  File "<input>", line 1, in <module>
Found 0 supply voltage channels.
Found 8 board ADC channels.
  File "C:\Users\dsuchane\AppData\Local\Continuum\Anaconda2\Lib\site-packages\rhd-1.0-py2.7.egg\rhd\load_intan_rhd_format.py", line 111, in read_data
    dtype=np.uint16)
Found 16 board digital input channels.
MemoryError
Found 0 board digital output channels.
Found 0 temperature sensors channels.
File contains 818.856 seconds of data.  Amplifiers were sampled at 20.00 kS/s.
Allocating memory for data...`

Is there any solution to this problem that you might suggest? 
Any help would be greatly appreciated.
Dymphie

**Comment by kylerbrown** [comment]
@IljaPilja I have never tried this package on Windows, so that could be the issue. @gfetterman, Any advice? Have there been improvements to the RHD library in bark that could help?

**Comment by gfetterman** [comment]
Yes, I have made changes to the RHD reading functions in bark (for @IljaPilja , that may be found on [the Margoliash lab github page for bark](https://github.com/margoliashlab/bark)) to speed them up and reduce their memory footprint. I can't guarantee that the changes would help with this problem, but running into a `MemoryError` suggests that they might.

If you use the updated function, note that it now acts as a generator of "chunks" of the data contained in the RHD file, rather than serving up the entire contents of the file at once. As the docstring indicates, you can set the chunk size it serves up to you to satisfy your memory restrictions.
